sprout/models/columns.py
"""Module defining the Columns model."""

from re import sub

import polars
from django.db import models

from sprout.models.data_types import DataTypes
from sprout.models.tables import Tables


class Columns(models.Model):
    """Model representing the metadata of columns."""

    tables = models.ForeignKey(Tables, on_delete=models.CASCADE)
    extracted_name = models.CharField(max_length=1000)
    machine_readable_name = models.CharField(max_length=200)
    display_name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    data_type = models.ForeignKey(DataTypes, on_delete=models.PROTECT)
    allow_missing_value = models.BooleanField()
    allow_duplicate_value = models.BooleanField()

    @staticmethod
    def create(table_id: int, series: polars.Series) -> "Columns":
        """Create Columns from polars.Series.

        Args:
            table_id: id of the table
            series: A polars series

        Returns:
            Columns: Columns instance based on series
        """
        return Columns(
            tables_id=table_id,
            extracted_name=series.name,
            machine_readable_name=_convert_to_snake_case(series.name),
            display_name=_convert_to_human_readable(series.name),
            description="",
            data_type=DataTypes.get_from_series(series),
            allow_missing_value=True,
            allow_duplicate_value=True,
        )


def _convert_to_snake_case(string: str) -> str:
    """This function takes a string and converts it to snake case.

    Args:
        string: A string to be converted to snake case

    Returns:
        A string that has been converted to snake case
    """
    # Remove trailing white spaces
    altered_string = string.strip()

    # Remove non-alphanumeric characters
    altered_string = sub(r"[^a-zA-Z0-9\s_-]+", "", altered_string)

    # Replace spaces and hyphens with underscores
    altered_string = sub(r"[\s-]+", "_", altered_string)

    # Convert camelCase to snake_case
    altered_string = sub(r"([a-z0-9])([A-Z])", r"\1_\2", altered_string)

    # Handle consecutive uppercase letters followed by lowercase letters (i.e., CAPS)
    altered_string = sub(r"([A-Z])([A-Z][a-z])", r"\1_\2", altered_string)

    return altered_string.lower()


def _convert_to_human_readable(string: str) -> str:
    """This function takes a string and converts it to human-readable title.

    Examples:
        snake_case --> Snake Case
        PascalCase --> Pascal Case
        CamelCase --> Camel Case
        lower case  --> Lower Case
        UPPER CASE --> Upper Case
        UPPER_CASE --> Upper Case

    Args:
        string: A string to be converted

    Returns:
        A string converted to human-readable title
    """
    # Add space to snake_case names
    string = sub("_", " ", string)

    # Add space to CamelCase names
    string = sub(r"([a-z])([A-Z])", r"\g<1> \g<2>", string)

    # Capitalize first letter in words
    return string.title()

sprout/templates/projects_id_metadata_id/create.html
{% extends 'includes/base.html' %}
{% load static %}

{% block headers %}
    <link rel="stylesheet" href="{% static 'css/metadata-stepper.css' %}" />
{% endblock headers %}

{% block content %}
  <h4>CREATE NEW METADATA</h4>
  <p>To create metadata (i.e., a space for your data), please go through the following steps</p>

  <!-- STEP 1 -->
  <div class="margin-bottom">
    <div>
      <div class="step-header {% if not request.GET.step or request.GET.step == '1' %}selected-step{% endif  %}">
        <div>1. Name and description</div>
        <i class="more">expand_more</i>
        <i class="less">expand_less</i>
      </div>
    </div>
    {% if not request.GET.step or request.GET.step == '1' %}
      {% include 'projects_id_metadata_id/step-name-and-description.html' %}
    {% endif %}

  </div>

  <!-- STEP 2 -->
  <div class="margin-bottom">
    <div >
      <div class="step-header {% if request.GET.step == '2' %}selected-step{% endif  %}">
        <div>2. File to base columns on</div>
        <i class="more">expand_more</i>
        <i class="less">expand_less</i>
      </div>
    </div>
    {% if request.GET.step == '2' %}
      {% include 'includes/file-drop-zone.html' %}
    {% endif %}
  </div>

  <!-- STEP 3 -->
  <div class="margin-bottom">
    <div>
      <div class="step-header {% if request.GET.step == '3' %}selected-step{% endif  %}">
        <div>3. Columns</div>
        <i class="more">expand_more</i>
        <i class="less">expand_less</i>
      </div>
    </div>
    {% if request.GET.step == '3' %}
      {% include 'projects_id_metadata_id/step-columns-update.html' %}
    {% endif %}
  </div>

  <div class="margin-bottom">
    <div >
      <div class="step-header {% if request.GET.step == '4' %}selected-step{% endif  %}">
        <div>4. Review and submit</div>
        <i class="more">expand_more</i>
        <i class="less">expand_less</i>
      </div>
    </div>
    {% if request.GET.step == '4' %}
      {% include 'projects_id_metadata_id/step-metadata-confirmation.html' %}
    {% endif %}
  </div>
  <!-- The file drop zone is included -->


  <!-- Dialog is only showing if upload_error is not empty -->
  {% if upload_error %}
    <div class="overlay blur active" data-ui="#dialog"></div>
    <dialog class="active" id="dialog">
      <div class="center-align">
        <i class="fill">error</i>
      </div>

      <h5 class="center-align">Woops!</h5>
      <div>
        Something went wrong: <br /><br /><b>{{ upload_error }}</b><br /><br /> Please add a csv file and try again
      </div>
      <nav class="right-align no-space">
        <button class="transparent link" data-ui="#dialog">OK</button>
      </nav>
    </dialog>
  {% endif %}

{% endblock %}

sprout/templates/projects_id_metadata_id/step-columns-update.html
{% load static %}
{% load widget_tweaks %}


<h2 style="margin-bottom: 20px">
  Headers for {{ tables.name }}
  <button class="circle small" data-ui="#help-ext_name">
    <i>question_mark</i>
  </button>
</h2>


<div class="row ">
  <div>
    <p>This is what we learnt about your data</p>
    <p>Please look through the extracted information about your data and fill in the missing fields</p>
  </div>
  <div class="max"></div>
  <nav class="no-space">
    <button class="border left-round fill" onclick="toggle(this)">
      <span>Card view</span>
    </button>
    <button class="border right-round" onclick="toggle(this)">
      <span>Table view</span>
    </button>
  </nav>
</div>

<!-- TABLE VIEW -->
<form id="metadata_view_table" hidden method="post" action="">
  {% csrf_token %}
  <table class="primary-table">
    <thead>
      <tr>
        <th>Extracted Name</th>
        <th>Display Name</th>
        <th>Description</th>
        <th>Data Type</th>
        <th>Excluded</th>
      </tr>
    </thead>
    <tbody>
      {% for form in forms %}
        <tr>
          <td>{{ form.instance.extracted_name }}</td>
          <td>{{ form.display_name|attr:'tabindex:2' }}</td>
          <td style="overflow: hidden;">{{ form.description|attr:'tabindex:3' }}</td>
          <td style="overflow: hidden;">{{ form.data_type|attr:'tabindex:4' }}</td>
          <td style="overflow: hidden;">{{ form.excluded|attr:'tabindex:5'|attr:'onclick:toggleExcluded(event)' }}</td>
          <input type="hidden" name="{{ form.prefix }}-id" value="{{ form.instance.id }}" />
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="row right-align" >
    <button type="submit" tabindex="10">Continue</button>
  </div>
</form>

<!-- GRID VIEW -->
<form id="metadata_view_grid" method="post" action="">
  {% csrf_token %}
  <div class="row wrap">
    {% for column in columns %}
      <!-- CARD -->
      <article class="row card">
        <!-- OVERLAY (when marked as excluded) -->
        <div hidden id="overlay_{{ column.id }}" style="position: absolute; width: 100%; height: 100%">
          <div style="position: relative; width: 100%; height: 100%; left: -16px; z-index: 10; background: rgba(0, 0, 0, 0.75)">
            <div class="middle">
              <div style="text-align: center; color: antiquewhite; font-weight: bold; font-size: 1.5rem">Excluded!</div>
            </div>
          </div>
        </div>

        <!-- CARD CONTENT -->
        <div style="min-width: 0; flex: 1; padding-top: 20px">
          <div class="row" style="margin-bottom: 20px">
            <h3 class="max card-header">{{ column.extracted_name }}</h3>
            <label class="checkbox icon" style="z-index: 11">
              {{ column.form.excluded|attr:'tabindex:5'|attr:'onclick:toggleExcluded(event)' }}
              <span>
                <i>delete</i>
                <i style="color: antiquewhite">undo</i>
              </span>
              <div id="tooltip_{{ column.id }}" class="tooltip">Exclude</div>
            </label>
          </div>
          <div class="field label small border" style="margin-bottom: 20px">
            {{ column.form.display_name|attr:'tabindex:1' }}
            <label>Display name</label>
          </div>

          <div hidden>{{ column.form.machine_readable_name|attr:'tabindex:2' }}</div>

          <div class="field label suffix border" style="margin-bottom: 20px">
            {{ column.form.data_type|attr:'tabindex:3' }}
            <label>Type</label>
            <i>arrow_drop_down</i>
          </div>

          <div class="field label small border" style="margin-bottom: 20px">
            {{ column.form.description|attr:'tabindex:4'|attr:'class:active' }}
            <label class="active">Description</label>
          </div>

          <div style="min-width: 0">
            <p style="color: grey; font-size: 0.75rem; font-weight: bold; margin-bottom: 5px">Preview (showing up to 5 unique values):</p>
            {% for cell in column.data %}
              <p style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap">{{ cell }}</p>
            {% endfor %}
          </div>
        </div>
      </article>
    {% endfor %}
  </div>

  <div class="row right-align">
    <button type="submit" tabindex="10">Continue</button>
  </div>
</form>

<!-- Help dialog -->
<dialog class="dialog" id="help-ext_name">
  <h5 class="center-align">Fields</h5>
  <dl>
    <dt>Extracted Name</dt>
    <dd>The column name extracted from the first file uploaded. This can't be changed.</dd>
    <dt>Machine-Readable Name</dt>
    <dd>The name that you would like the column/variable to have going forward. This name can't include spaces or special characters.</dd>
    <dt>Display Name</dt>
    <dd>The name that can be used when you want to show the data in a more 'human readable' way. An example could be the variable b60, which you could give the more descriptive display name Blood taken after 60 minutes.</dd>
    <dt>Description</dt>
    <dd>A short description of the column/variable, including things like when a sample is taken, the unit, etc.</dd>
    <dt>Data Type</dt>
    <dd>This is the data type of the variable, this will need to be defined in order for data to be saved, what you see in the list initially is the best guess from Seedcase Sprout based on the data you uploaded.</dd>
  </dl>
  <p>
    See our <a href="https://design.seedcase-project.org/"><span style="color:blue">documentation</span></a> for more information.
  </p>
  <nav class="right-align no-space">
    <a class="transparent link" data-ui="#help-ext_name">Close</a>
  </nav>
</dialog>

<script>
  let moveInputValues = (source, target) => {
    for (let sourceInput of source.querySelectorAll('input[id],select[id]')) {
      const targetInput = target.querySelector('#' + sourceInput.id)
      if (targetInput) {
        targetInput.value = sourceInput.value
        targetInput.checked = sourceInput.checked
      }
    }
  }

  let toggle = (button) => {
    let element_table = document.getElementById('metadata_view_table')
    let element_grid = document.getElementById('metadata_view_grid')

    document.querySelector("button.fill").classList.remove("fill")

    button.classList.add("fill")
    if (button.innerText.includes("Table")) {
      element_table.hidden = false
      element_grid.hidden = true

      moveInputValues(element_grid, element_table)
    } else {
      element_grid.hidden = false
      element_table.hidden = true

      moveInputValues(element_table, element_grid)
    }
  }

  let toggleExcluded = (event) => {
    const columnId = event.target.id.replace('id_', '').replace('-excluded', '')

    const overlay = document.getElementById('overlay_' + columnId)
    overlay.hidden = !overlay.hidden

    const tooltip = document.getElementById('tooltip_' + columnId)
    tooltip.innerText = overlay.hidden ? 'Exclude' : 'Undo exclude'

    // description is not required if column is excluded
    document.getElementsByName(columnId + '-description').forEach((d) => (d.required = overlay.hidden))
  }
</script>

sprout/templates/projects_id_metadata_id/step-metadata-confirmation.html
<h4>Summary of metadata</h4>
<p><span class="bold">Name:</span> {{ table.name }}</p>
<p><span class="bold">Description:</span> {{ table.description }}</p>
<p><span class="bold">Based on file:</span> {{ table.original_file_name }}</p>
<p><span class="bold">Number of included columns:</span> {{ table.columns_set.all.count }}</p>
<p><span class="bold">Included column names:</span>
  {% for column in table.columns_set.all %}
    {{ column.display_name }},
  {% endfor %}
</p>

<div class="row center-align">
  <a href="{% url 'projects-id-metadata-view' %}"><button>Done</button></a>
</div>